In [8]:
# Task 1: Create a 1D array of numbers from 0-9
import numpy as np

jo_array = np.array([0,1,2,3,4,5,6,7,8,9])
print (jo_array)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
# Task 2: Create a 3x3 NumPy array of all Boolean value Trues

ones = np.ones(9)
ones_2 = ones.reshape(3,3)
print (ones_2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
# Task 3: Extract all odd numbers in an array of 1-10

odds = np.arange(1,10,2)
print (odds)

[1 3 5 7 9]


In [26]:
# Task 4: Replace all odd numbers in an array of 1-10 with the value -1

jo_array = np.array([1,2,3,4,5,6,7,8,9,10])
jo_array[jo_array%2==1] = -1
print (jo_array)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [27]:
# Task 5: Convert a 1D array to a 2D array with 2 rows

jo_array = np.array([0,1,2,3,4,5,6,7,8,9])
jo_array_2 = array.reshape(2, 5)
print (jo_array_2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [20]:
# Task 6a: Create two arrays a and b, stack these two arrays vertically

a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)

print (a)
print (b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [21]:
# Task 6b: Create two arrays a and b, stack these two arrays vertically use the np.dot to calculate totals

a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.dot(a,b)

print (c)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [22]:
# Task 6c: Create two arrays a and b, stack these two arrays vertically use the np.sum to calculate totals

a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.dot(a,b)
sum = np.sum(c)
print (sum)

1944
